;;; fruity-theme.el --- A port of vim's fruity theme. -*- lexical-binding: t -*-

;; Copyright (C) 2017 James Nguyen

;; Author: James Nguyen <james@jojojames.com>
;; Maintainer: James Nguyen <james@jojojames.com>
;; URL: https://github.com/jojojames/fruity-theme
;; Version: 0.0.5
;; Package-Requires: ((emacs "29.1"))
;; Keywords: emacs, tools, theme
;; HomePage: https://github.com/jojojames/fruity-theme

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:

;; A port of the Fruity theme for Vim to Emacs.

;;; Credits:

;; https://github.com/mitsuhiko/fruity-vim-colorscheme

;;; Code:

(defgroup fruity-theme nil
  "Fruity theme customizations."
  :group 'faces
  :prefix "fruity-")

(defcustom fruity-want-transparent-line-numbers t
  "If non-nil, `line-number' backgrounds match the buffer background.
If nil, a distinct darker gutter color is used."
  :type 'boolean
  :group 'fruity-theme)

(defcustom fruity-want-dark-modeline t
  "If non-nil, use the dark modeline palette (blue on dark bg).
If nil, use the original light modeline (dark text on light bg)
from fruity-theme v0.0.1."
  :type 'boolean
  :group 'fruity-theme)

(deftheme fruity "Port of fruity theme")

(let* (;; Base surfaces
      (fg           "#ffffff")
      (bg           "#001217")
      (bg-alt       "#0a1323") ; dim accent bg (comment bg)
      (bg-sign      "#002B36") ; sign column
      (bg-cursor    "#001C24") ; cursor line / hl-line
      (bg-column    "#011c25") ; fill-column-indicator
      (bg-visual    "#004254") ; region / selection / tab-line
      (bg-pmenu     "#0D4854") ; completion / tooltip
      (bg-pmenu-sel "#146E80") ; selected completion
      (bg-wild      "#324A61") ; wildmenu bg / tooltip bg
      (fg-wild      "#D3E3F2") ; wildmenu fg / tooltip fg
      (fg-dim       "#aaaaaa")
      (fg-dimmer    "#444444")
      (fg-dimmest   "#506070")

      ;; Search
      (search-fg     "#161C00")
      (search-bg     "#BEED00")
      (isearch-fg    "#004357")
      (isearch-bg    "#B8EFFF")

      ;; Paren match
      (paren-fg      "#CEF2D0")
      (paren-bg      "#105715")

      ;; Status signals
      (warning-fg    "#ED9A09")
      (warning-bg    "#422A00")
      (error-fg      "#EB1515")
      (error-bg      "#3B0000")
      (todo-fg       "#e50808")
      (todo-bg       "#520000")
      (success-fg    "#5BCF21")

      ;; Git / diff
      (git-add       "#5BCF21")
      (git-change    "#CF9A21")
      (git-delete    "#CF2121")

      ;; Syntax palette (fruity.vim, extended)
      (string        "#0086d2")
      (constant      "#007DC4")
      (number        "#0086f7")
      (func          "#1BB3FF")
      (preproc       "#ff0007")
      (variable      "#e90819")
      (reference     "#e90819")
      (comment-fg    "#00d2ff")
      (comment-bg    "#0a1323")
      (doc-fg        "#8AF7FF")
      (type          "#00A8A0")
      (identifier    "#79E33B")
      (keyword       "#79E33B")
      (label         "#BD55E6")
      (operator      "#8ECFDD")
      (negation      "#fd8900")
      (regex         "#92cd35")
      (macro         "#AAFF42")
      (pink          "#FF15A1")
      (magenta       "#BD55E6")
      (magenta-soft  "#DC8CC3")
      (orange        "#fd8900")
      (orange-soft   "#dd7700")
      (cyan-bright   "#00bdec")
      (blue-soft     "#5CB6ED")
      (green-soft    "#8FB28F")

      ;; Aliases used throughout
      (subtle-1      "#1BB3FF")
      (subtle-2      "#0086d2")

      ;; Derived from user options
      (linenum-bg     (if fruity-want-transparent-line-numbers bg "#00252e"))
      (ml-fg          (if fruity-want-dark-modeline subtle-1 "#00243B"))
      (ml-bg          (if fruity-want-dark-modeline bg-alt "#C1CFDE"))
      (ml-inactive-fg (if fruity-want-dark-modeline subtle-2 "#506070"))
      (ml-inactive-bg (if fruity-want-dark-modeline bg-alt "#DFE9F2")))

  (custom-theme-set-faces
   'fruity

;;;; Basic coloring
   `(default ((t (:foreground ,fg :background ,bg))))
   `(bold ((t (:weight bold))))
   `(italic ((t (:slant italic))))
   `(bold-italic ((t (:weight bold :slant italic))))
   `(underline ((t (:underline t))))
   `(shadow ((t (:foreground ,fg-dim))))
   `(button ((t (:foreground ,subtle-1 :underline t))))
   `(link ((t (:foreground ,subtle-1 :underline t))))
   `(link-visited ((t (:foreground ,magenta :underline t))))
   `(cursor ((t (:background "#aaaaaa"))))
   `(fringe ((t (:foreground ,fg :background ,bg))))
   `(vertical-border ((t (:foreground ,subtle-2))))
   `(window-divider ((t (:foreground ,subtle-2))))
   `(window-divider-first-pixel ((t (:inherit window-divider))))
   `(window-divider-last-pixel ((t (:inherit window-divider))))
   `(tooltip ((t (:foreground ,fg-wild :background ,bg-wild))))
   `(region ((t (:background ,bg-visual :extend t))))
   `(secondary-selection ((t (:background ,bg-pmenu :extend t))))
   `(hl-line ((t (:background ,bg-cursor :inverse-video nil :extend t))))
   `(highlight ((t (:background ,bg-cursor :extend t))))
   `(lazy-highlight ((t (:foreground ,fg :background ,bg-visual))))
   `(trailing-whitespace ((t (:underline (:style wave :color "white")))))
   `(fill-column-indicator ((t (:foreground ,bg-column))))
   `(minibuffer-prompt ((t (:foreground ,comment-fg))))
   `(escape-glyph ((t (:foreground ,error-fg :background ,error-bg))))
   `(homoglyph ((t (:foreground ,orange))))
   `(nobreak-space ((t (:foreground ,fg-dim :underline t))))
   `(nobreak-hyphen ((t (:foreground ,fg-dim))))

;;;; Header / mode line / tab line
   `(header-line ((t (:foreground ,fg :background "#333333" :extend t))))
   `(mode-line
     ((t (:foreground ,ml-fg :background ,ml-bg
                      :box (:color ,ml-bg :line-width 5)))))
   `(mode-line-inactive
     ((t (:foreground ,ml-inactive-fg :background ,ml-inactive-bg
                      :box (:color ,ml-inactive-bg :line-width 5)))))
   `(mode-line-emphasis ((t (:foreground ,ml-fg :weight bold))))
   `(mode-line-highlight ((t (:foreground ,pink :weight bold))))
   `(mode-line-buffer-id ((t (:foreground ,ml-fg :weight bold))))
   `(tab-bar ((t (:foreground ,fg :background ,bg-visual))))
   `(tab-bar-tab ((t (:foreground ,fg :background ,bg :weight bold))))
   `(tab-bar-tab-inactive ((t (:foreground ,fg-dim :background ,bg-visual))))
   `(tab-line ((t (:foreground ,fg :background ,bg-visual))))
   `(tab-line-tab ((t (:foreground ,fg :background ,bg :weight bold))))
   `(tab-line-tab-inactive ((t (:foreground ,fg-dim :background ,bg-visual))))
   `(tab-line-tab-current ((t (:foreground ,fg :background ,bg :weight bold))))
   `(tab-line-highlight ((t (:foreground ,fg :background ,bg-pmenu-sel))))

;;;; Line numbers
   `(line-number ((t (:foreground ,fg-dim :background ,linenum-bg))))
   `(line-number-current-line ((t (:foreground ,fg :background ,linenum-bg :weight bold))))
   `(line-number-major-tick ((t (:foreground ,fg-dim :background ,linenum-bg :weight bold))))
   `(line-number-minor-tick ((t (:foreground ,fg-dimmer :background ,linenum-bg))))

;;;; Font lock
   `(font-lock-builtin-face ((t (:foreground ,operator))))
   `(font-lock-comment-delimiter-face
     ((t (:foreground ,comment-fg :background ,comment-bg :slant italic))))
   `(font-lock-comment-face ((t (:foreground ,comment-fg :slant italic))))
   `(font-lock-constant-face ((t (:foreground ,constant))))
   `(font-lock-doc-face ((t (:foreground ,doc-fg :slant italic))))
   `(font-lock-doc-string-face ((t (:foreground ,string))))
   `(font-lock-function-name-face ((t (:foreground ,func))))
   `(font-lock-keyword-face ((t (:foreground ,keyword :weight bold))))
   `(font-lock-negation-char-face ((t (:foreground ,negation))))
   `(font-lock-number-face ((t (:foreground ,number :weight bold))))
   `(font-lock-preprocessor-face ((t (:foreground ,preproc :weight bold))))
   `(font-lock-reference-face ((t (:foreground ,reference))))
   `(font-lock-regexp-grouping-backslash ((t (:foreground ,label))))
   `(font-lock-regexp-grouping-construct ((t (:foreground ,label))))
   `(font-lock-string-face ((t (:foreground ,string))))
   `(font-lock-type-face ((t (:foreground ,type))))
   `(font-lock-variable-name-face ((t (:foreground ,variable))))
   `(font-lock-warning-face
     ((t (:foreground ,todo-fg :background ,todo-bg :weight bold))))
   `(font-lock-operator-face ((t (:foreground ,operator))))
   `(font-lock-property-name-face ((t (:foreground ,identifier))))
   `(font-lock-punctuation-face ((t (:foreground ,operator))))
   `(font-lock-bracket-face ((t (:foreground ,operator))))
   `(font-lock-delimiter-face ((t (:foreground ,operator))))
   `(font-lock-escape-face ((t (:foreground ,negation))))
   `(font-lock-misc-punctuation-face ((t (:foreground ,operator))))
   `(font-lock-regexp-face ((t (:foreground ,regex))))
   `(font-lock-function-call-face ((t (:foreground ,func))))
   `(font-lock-property-use-face ((t (:foreground ,identifier))))
   `(font-lock-variable-use-face ((t (:foreground ,variable))))

;;;; Signals
   `(success ((t (:foreground ,success-fg :weight bold))))
   `(warning ((t (:foreground ,warning-fg :background ,warning-bg))))
   `(error ((t (:foreground ,error-fg :background ,error-bg :weight bold))))
   `(next-error ((t (:inherit error :extend t))))
   `(query-replace ((t (:inherit isearch))))

;;;; Search / paren
   `(isearch ((t (:foreground ,search-fg :background ,search-bg :weight bold))))
   `(isearch-fail ((t (:foreground ,error-fg :background ,error-bg :weight bold))))
   `(isearch-group-1 ((t (:foreground ,search-fg :background ,search-bg :weight bold))))
   `(isearch-group-2 ((t (:foreground ,isearch-fg :background ,isearch-bg :weight bold))))
   `(match ((t (:foreground ,isearch-fg :background ,isearch-bg :weight bold))))
   `(show-paren-match ((t (:foreground ,paren-fg :background ,paren-bg :weight bold))))
   `(show-paren-match-expression ((t (:background ,paren-bg :extend t))))
   `(show-paren-mismatch ((t (:foreground ,error-fg :background ,error-bg))))

;;;; Widgets
   `(widget-field ((t (:foreground ,fg :background ,bg-pmenu))))
   `(widget-single-line-field ((t (:foreground ,fg :background ,bg-pmenu))))
   `(widget-button ((t (:foreground ,subtle-1 :underline t :weight bold))))
   `(widget-button-pressed ((t (:foreground ,pink :weight bold))))
   `(widget-documentation ((t (:foreground ,green-soft))))
   `(widget-inactive ((t (:foreground ,fg-dim))))

;;;; Customize
   `(custom-button
     ((t (:foreground ,fg :background ,bg-pmenu
                      :box (:line-width 2 :style released-button)))))
   `(custom-button-mouse
     ((t (:foreground ,fg :background ,bg-pmenu-sel
                      :box (:line-width 2 :style released-button)))))
   `(custom-button-pressed
     ((t (:foreground ,fg :background ,bg-pmenu-sel
                      :box (:line-width 2 :style pressed-button)))))
   `(custom-variable-tag ((t (:foreground ,subtle-1 :weight bold))))
   `(custom-group-tag ((t (:foreground ,subtle-1 :weight bold :height 1.2))))
   `(custom-group-subtitle ((t (:foreground ,subtle-1 :weight bold))))
   `(custom-state ((t (:foreground ,success-fg))))
   `(custom-comment ((t (:inherit font-lock-comment-face))))
   `(custom-comment-tag ((t (:foreground ,comment-fg))))
   `(custom-changed ((t (:foreground ,orange))))
   `(custom-modified ((t (:foreground ,orange))))
   `(custom-invalid ((t (:foreground ,error-fg :background ,error-bg))))
   `(custom-set ((t (:foreground ,success-fg))))
   `(custom-link ((t (:inherit link))))
   `(custom-visibility ((t (:inherit link))))
   `(custom-themed ((t (:foreground ,subtle-1))))

;;;; Completions (built-in)
   `(completions-annotations ((t (:foreground ,fg-dim :slant italic))))
   `(completions-common-part ((t (:foreground ,subtle-1))))
   `(completions-first-difference ((t (:foreground ,pink :weight bold))))
   `(completions-group-title ((t (:foreground ,subtle-1 :weight bold))))
   `(completions-group-separator ((t (:foreground ,fg-dimmer :strike-through t))))
   `(completions-highlight ((t (:background ,bg-pmenu-sel :extend t))))

;;;; Help
   `(help-argument-name ((t (:foreground ,identifier :slant italic))))
   `(help-key-binding
     ((t (:foreground ,subtle-1 :background ,bg-alt
                      :box (:line-width -1 :color ,subtle-2)))))

;;;; Info
   `(Info-quoted ((t (:inherit font-lock-constant-face))))
   `(info-title-1 ((t (:foreground ,pink :weight bold :height 1.2))))
   `(info-title-2 ((t (:foreground ,subtle-1 :weight bold :height 1.15))))
   `(info-title-3 ((t (:foreground ,identifier :weight bold :height 1.1))))
   `(info-title-4 ((t (:foreground ,orange :weight bold))))
   `(info-node ((t (:foreground ,subtle-1 :weight bold))))
   `(info-menu-header ((t (:foreground ,subtle-1 :weight bold))))
   `(info-menu-star ((t (:foreground ,orange))))
   `(info-xref ((t (:inherit link))))
   `(info-xref-visited ((t (:inherit link-visited))))

;;;; Compilation
   `(compilation-column-face ((t (:foreground ,orange))))
   `(compilation-column-number ((t (:foreground ,orange))))
   `(compilation-line-face ((t (:foreground ,identifier))))
   `(compilation-line-number ((t (:foreground ,identifier))))
   `(compilation-error ((t (:foreground ,error-fg :weight bold))))
   `(compilation-warning ((t (:foreground ,warning-fg :weight bold))))
   `(compilation-info ((t (:foreground ,subtle-1 :weight bold))))
   `(compilation-enter-directory-face ((t (:foreground ,identifier))))
   `(compilation-leave-directory-face ((t (:foreground ,identifier))))
   `(compilation-message-face ((t (:foreground ,subtle-1))))
   `(compilation-mode-line-exit ((t (:foreground ,success-fg :weight bold))))
   `(compilation-mode-line-fail ((t (:foreground ,error-fg :weight bold))))
   `(compilation-mode-line-run ((t (:foreground ,orange :weight bold))))

;;;; Whitespace
   `(whitespace-space ((t (:background ,bg :foreground ,fg-dimmer))))
   `(whitespace-hspace ((t (:background ,bg :foreground ,fg-dimmer))))
   `(whitespace-tab ((t (:underline (:style wave :color "white")))))
   `(whitespace-newline ((t (:foreground ,fg-dimmer))))
   `(whitespace-trailing ((t (:underline (:style wave :color "white")))))
   `(whitespace-line ((t (:underline (:style wave :color "white")))))
   `(whitespace-space-before-tab ((t (:background ,todo-bg))))
   `(whitespace-indentation ((t (:background ,comment-bg))))
   `(whitespace-empty ((t (:foreground ,fg-dimmer :background ,bg-alt))))
   `(whitespace-big-indent ((t (:background ,todo-bg))))

;;;; Dired / dired-sidebar / dired-subtree
   `(dired-directory ((t (:foreground ,identifier :weight bold))))
   `(dired-symlink ((t (:foreground ,magenta :slant italic))))
   `(dired-header ((t (:foreground ,subtle-1 :weight bold))))
   `(dired-ignored ((t (:foreground ,fg-dim))))
   `(dired-mark ((t (:foreground ,orange :weight bold))))
   `(dired-marked ((t (:foreground ,orange :weight bold))))
   `(dired-flagged ((t (:foreground ,error-fg :weight bold))))
   `(dired-perm-write ((t (:foreground ,warning-fg))))
   `(dired-warning ((t (:foreground ,warning-fg :weight bold))))
   `(dired-broken-symlink ((t (:foreground ,error-fg :weight bold))))
   `(dired-set-id ((t (:foreground ,warning-fg))))
   `(dired-special ((t (:foreground ,magenta))))

;;;; all-the-icons-dired
   `(all-the-icons-dired-dir-face ((t (:foreground ,identifier))))

;;;; Diff mode
   `(diff-added ((t (:foreground ,git-add :background ,bg-alt :extend t))))
   `(diff-removed ((t (:foreground ,git-delete :background ,bg-alt :extend t))))
   `(diff-changed ((t (:foreground ,git-change :background ,bg-alt :extend t))))
   `(diff-context ((t (:foreground ,fg-dim :extend t))))
   `(diff-header ((t (:foreground ,subtle-1 :weight bold :extend t))))
   `(diff-file-header ((t (:foreground ,pink :weight bold :extend t))))
   `(diff-function ((t (:foreground ,func :weight bold :extend t))))
   `(diff-hunk-header ((t (:foreground ,orange :weight bold :extend t))))
   `(diff-index ((t (:foreground ,subtle-1 :extend t))))
   `(diff-indicator-added ((t (:foreground ,git-add :extend t))))
   `(diff-indicator-removed ((t (:foreground ,git-delete :extend t))))
   `(diff-indicator-changed ((t (:foreground ,git-change :extend t))))
   `(diff-nonexistent ((t (:foreground ,fg-dim :extend t))))
   `(diff-refine-added ((t (:foreground ,git-add :background ,paren-bg :weight bold))))
   `(diff-refine-removed ((t (:foreground ,git-delete :background ,error-bg :weight bold))))
   `(diff-refine-changed ((t (:foreground ,git-change :background ,warning-bg :weight bold))))

;;;; diff-hl
   `(diff-hl-insert ((t (:foreground ,git-add :background ,bg-sign))))
   `(diff-hl-delete ((t (:foreground ,git-delete :background ,bg-sign))))
   `(diff-hl-change ((t (:foreground ,git-change :background ,bg-sign))))

;;;; Ediff
   `(ediff-current-diff-A ((t (:foreground ,git-delete :background ,error-bg :extend t))))
   `(ediff-current-diff-B ((t (:foreground ,git-add :background ,paren-bg :extend t))))
   `(ediff-current-diff-C ((t (:foreground ,git-change :background ,warning-bg :extend t))))
   `(ediff-current-diff-Ancestor ((t (:foreground ,fg :background ,bg-visual :extend t))))
   `(ediff-even-diff-A ((t (:background ,bg-cursor :extend t))))
   `(ediff-even-diff-B ((t (:background ,bg-cursor :extend t))))
   `(ediff-even-diff-C ((t (:background ,bg-cursor :extend t))))
   `(ediff-even-diff-Ancestor ((t (:background ,bg-cursor :extend t))))
   `(ediff-odd-diff-A ((t (:background ,bg-alt :extend t))))
   `(ediff-odd-diff-B ((t (:background ,bg-alt :extend t))))
   `(ediff-odd-diff-C ((t (:background ,bg-alt :extend t))))
   `(ediff-odd-diff-Ancestor ((t (:background ,bg-alt :extend t))))
   `(ediff-fine-diff-A ((t (:foreground ,git-delete :background ,error-bg :weight bold))))
   `(ediff-fine-diff-B ((t (:foreground ,git-add :background ,paren-bg :weight bold))))
   `(ediff-fine-diff-C ((t (:foreground ,git-change :background ,warning-bg :weight bold))))

;;;; ANSI colors (term, vterm, eshell)
   `(ansi-color-black        ((t (:foreground "black"   :background "black"))))
   `(ansi-color-red          ((t (:foreground ,preproc  :background ,preproc))))
   `(ansi-color-green        ((t (:foreground ,identifier :background ,identifier))))
   `(ansi-color-yellow       ((t (:foreground ,orange   :background ,orange))))
   `(ansi-color-blue         ((t (:foreground ,subtle-1 :background ,subtle-1))))
   `(ansi-color-magenta      ((t (:foreground ,pink     :background ,pink))))
   `(ansi-color-cyan         ((t (:foreground ,comment-fg :background ,comment-fg))))
   `(ansi-color-white        ((t (:foreground ,fg       :background ,fg))))
   `(ansi-color-bright-black   ((t (:foreground ,fg-dimmest :background ,fg-dimmest))))
   `(ansi-color-bright-red     ((t (:foreground ,pink   :background ,pink))))
   `(ansi-color-bright-green   ((t (:foreground ,macro  :background ,macro))))
   `(ansi-color-bright-yellow  ((t (:foreground ,search-bg :background ,search-bg))))
   `(ansi-color-bright-blue    ((t (:foreground ,cyan-bright :background ,cyan-bright))))
   `(ansi-color-bright-magenta ((t (:foreground ,magenta :background ,magenta))))
   `(ansi-color-bright-cyan    ((t (:foreground ,isearch-bg :background ,isearch-bg))))
   `(ansi-color-bright-white   ((t (:foreground "white" :background "white"))))

;;;; Terminal / vterm
   `(term-color-black ((t (:foreground "black" :background "black"))))
   `(term-color-red ((t (:foreground ,preproc :background ,preproc))))
   `(term-color-green ((t (:foreground ,identifier :background ,identifier))))
   `(term-color-yellow ((t (:foreground ,orange :background ,orange))))
   `(term-color-blue ((t (:foreground ,subtle-1 :background ,subtle-1))))
   `(term-color-magenta ((t (:foreground ,pink :background ,pink))))
   `(term-color-cyan ((t (:foreground ,comment-fg :background ,comment-fg))))
   `(term-color-white ((t (:foreground ,fg :background ,fg))))
   `(term ((t (:foreground ,fg :background ,bg))))
   `(vterm-color-default ((t (:foreground ,fg :background ,bg))))
   `(vterm-color-black ((t (:foreground "black" :background "#333333"))))
   `(vterm-color-red ((t (:foreground ,preproc :background ,preproc))))
   `(vterm-color-green ((t (:foreground ,identifier :background ,identifier))))
   `(vterm-color-yellow ((t (:foreground ,orange :background ,orange))))
   `(vterm-color-blue ((t (:foreground ,subtle-1 :background ,subtle-1))))
   `(vterm-color-magenta ((t (:foreground ,pink :background ,pink))))
   `(vterm-color-cyan ((t (:foreground ,comment-fg :background ,comment-fg))))
   `(vterm-color-white ((t (:foreground ,fg :background ,fg))))
   `(vterm-color-inverse-video ((t (:background ,bg))))

;;;; Eshell
   `(eshell-prompt ((t (:foreground ,pink :weight bold))))
   `(eshell-ls-archive ((t (:foreground ,magenta :weight bold))))
   `(eshell-ls-backup ((t (:foreground ,fg-dim))))
   `(eshell-ls-clutter ((t (:foreground ,orange :weight bold))))
   `(eshell-ls-directory ((t (:foreground ,identifier :weight bold))))
   `(eshell-ls-executable ((t (:foreground ,success-fg :weight bold))))
   `(eshell-ls-missing ((t (:foreground ,error-fg :weight bold))))
   `(eshell-ls-product ((t (:foreground ,orange))))
   `(eshell-ls-readonly ((t (:foreground ,warning-fg))))
   `(eshell-ls-special ((t (:foreground ,pink :weight bold))))
   `(eshell-ls-symlink ((t (:foreground ,magenta :slant italic))))
   `(eshell-ls-unreadable ((t (:foreground ,fg-dim))))

;;;; eww
   '(eww-invalid-certificate ((t (:inherit error))))
   '(eww-valid-certificate   ((t (:inherit success))))
   `(eww-form-submit
     ((t (:foreground ,fg :background ,bg-pmenu
                      :box (:line-width 2 :style released-button)))))
   `(eww-form-text ((t (:foreground ,fg :background ,bg-pmenu))))
   `(eww-form-textarea ((t (:foreground ,fg :background ,bg-pmenu))))

;;;; grep / deadgrep / ag
   `(grep-context-face ((t (:foreground ,fg-dim))))
   `(grep-error-face ((t (:foreground ,error-fg :weight bold :underline t))))
   `(grep-hit-face ((t (:foreground ,subtle-1))))
   `(grep-match-face ((t (:foreground ,search-bg :weight bold))))
   `(deadgrep-filename-face ((t (:foreground ,pink :weight bold))))
   `(deadgrep-meta-face ((t (:foreground ,fg-dim))))
   `(deadgrep-match-face ((t (:foreground ,search-fg :background ,search-bg :weight bold))))
   `(deadgrep-search-term-face ((t (:foreground ,pink :weight bold))))
   `(deadgrep-regexp-metachar-face ((t (:foreground ,label :weight bold))))

;;;; Flycheck
   `(flycheck-error
     ((t (:foreground ,error-fg :background ,error-bg
                      :underline (:style wave :color ,error-fg)))))
   `(flycheck-warning
     ((t (:foreground ,warning-fg :background ,warning-bg
                      :underline (:style wave :color ,warning-fg)))))
   `(flycheck-info ((t (:underline (:style wave :color ,success-fg)))))
   `(flycheck-fringe-error ((t (:foreground ,error-fg))))
   `(flycheck-fringe-warning ((t (:foreground ,warning-fg))))
   `(flycheck-fringe-info ((t (:foreground ,success-fg))))
   `(flycheck-error-list-error ((t (:inherit error))))
   `(flycheck-error-list-warning ((t (:inherit warning))))
   `(flycheck-error-list-info ((t (:foreground ,subtle-1))))
   `(flycheck-error-list-line-number ((t (:foreground ,identifier))))
   `(flycheck-error-list-column-number ((t (:foreground ,identifier))))
   `(flycheck-error-list-id ((t (:foreground ,type))))
   `(flycheck-error-list-id-with-explainer
     ((t (:inherit flycheck-error-list-id :box (:style released-button)))))
   `(flycheck-error-list-checker-name ((t (:foreground ,func))))
   `(flycheck-error-list-highlight
     ((t (:background ,bg-cursor :underline (:style wave :color ,error-bg)))))

;;;; Hi-lock
   `(hi-blue    ((t (:background ,comment-fg :foreground ,bg))))
   `(hi-green   ((t (:background ,identifier :foreground ,bg))))
   `(hi-pink    ((t (:background ,pink :foreground ,bg))))
   `(hi-yellow  ((t (:background ,search-bg :foreground ,bg))))
   `(hi-blue-b  ((t (:foreground ,subtle-1 :weight bold))))
   `(hi-green-b ((t (:foreground ,identifier :weight bold))))
   `(hi-red-b   ((t (:foreground ,preproc :weight bold))))
   `(hi-black-b ((t (:foreground ,fg-dim :weight bold))))
   `(hi-black-hb ((t (:foreground ,fg-dim :background ,bg-cursor :weight bold))))

;;;; Outline
   `(outline-1 ((t (:foreground ,pink :weight bold))))
   `(outline-2 ((t (:foreground ,subtle-1 :weight bold))))
   `(outline-3 ((t (:foreground ,identifier :weight bold))))
   `(outline-4 ((t (:foreground ,orange :weight bold))))
   `(outline-5 ((t (:foreground ,magenta :weight bold))))
   `(outline-6 ((t (:foreground ,type :weight bold))))
   `(outline-7 ((t (:foreground ,blue-soft :weight bold))))
   `(outline-8 ((t (:foreground ,magenta-soft :weight bold))))

;;;; Org mode
   `(org-level-1 ((t (:foreground ,pink :weight bold))))
   `(org-level-2 ((t (:foreground ,subtle-1 :weight bold))))
   `(org-level-3 ((t (:foreground ,identifier :weight bold))))
   `(org-level-4 ((t (:foreground ,orange :weight bold))))
   `(org-level-5 ((t (:foreground ,magenta :weight bold))))
   `(org-level-6 ((t (:foreground ,type :weight bold))))
   `(org-level-7 ((t (:foreground ,blue-soft :weight bold))))
   `(org-level-8 ((t (:foreground ,magenta-soft :weight bold))))
   `(org-document-title ((t (:foreground ,fg :weight bold :height 1.3))))
   `(org-document-info ((t (:foreground ,subtle-1))))
   `(org-document-info-keyword ((t (:foreground ,fg-dim))))
   `(org-meta-line ((t (:foreground ,fg-dim :slant italic))))
   `(org-block ((t (:foreground ,fg :background ,bg-alt :extend t))))
   `(org-block-begin-line
     ((t (:foreground ,fg-dim :background ,bg-alt :slant italic :extend t))))
   `(org-block-end-line
     ((t (:foreground ,fg-dim :background ,bg-alt :slant italic :extend t))))
   `(org-quote ((t (:inherit org-block :slant italic))))
   `(org-verse ((t (:inherit org-block :slant italic))))
   `(org-code ((t (:foreground ,regex :background ,bg-alt))))
   `(org-verbatim ((t (:foreground ,string :background ,bg-alt))))
   `(org-link ((t (:inherit link))))
   `(org-footnote ((t (:foreground ,blue-soft :underline t))))
   `(org-date ((t (:foreground ,blue-soft :underline t))))
   `(org-sexp-date ((t (:foreground ,blue-soft))))
   `(org-time-grid ((t (:foreground ,fg-dim))))
   `(org-todo ((t (:foreground ,todo-fg :weight bold :box t))))
   `(org-done ((t (:foreground ,success-fg :weight bold :box t))))
   `(org-headline-todo ((t (:foreground ,todo-fg))))
   `(org-headline-done ((t (:foreground ,fg-dim :strike-through t))))
   `(org-ellipsis ((t (:foreground ,fg-dim :underline nil))))
   `(org-drawer ((t (:foreground ,fg-dim))))
   `(org-special-keyword ((t (:foreground ,keyword))))
   `(org-table ((t (:foreground ,subtle-1 :background ,bg-alt))))
   `(org-table-header ((t (:foreground ,fg :background ,bg-visual :weight bold))))
   `(org-formula ((t (:foreground ,pink))))
   `(org-checkbox ((t (:foreground ,identifier :weight bold))))
   `(org-checkbox-statistics-todo ((t (:foreground ,todo-fg :weight bold))))
   `(org-checkbox-statistics-done ((t (:foreground ,success-fg :weight bold))))
   `(org-tag ((t (:foreground ,magenta :weight bold))))
   `(org-tag-group ((t (:inherit org-tag))))
   `(org-priority ((t (:foreground ,orange :weight bold))))
   `(org-warning ((t (:foreground ,warning-fg :weight bold))))
   `(org-scheduled ((t (:foreground ,identifier))))
   `(org-scheduled-today ((t (:foreground ,identifier :weight bold))))
   `(org-scheduled-previously ((t (:foreground ,orange))))
   `(org-upcoming-deadline ((t (:foreground ,orange))))
   `(org-deadline-announce ((t (:foreground ,warning-fg))))
   `(org-archived ((t (:foreground ,fg-dim))))
   `(org-hide ((t (:foreground ,bg))))
   `(org-indent ((t (:inherit (org-hide fixed-pitch)))))
   `(org-column ((t (:background ,bg-alt :extend t))))
   `(org-column-title ((t (:foreground ,subtle-1 :background ,bg-alt :weight bold :underline t))))
   `(org-latex-and-related ((t (:foreground ,subtle-1))))
   `(org-macro ((t (:foreground ,regex))))
   `(org-target ((t (:underline t))))
   `(org-clock-overlay ((t (:background ,bg-visual))))
   `(org-mode-line-clock ((t (:inherit mode-line))))
   `(org-mode-line-clock-overrun ((t (:foreground ,error-fg :inherit mode-line))))
   `(org-agenda-structure ((t (:foreground ,subtle-1 :weight bold))))
   `(org-agenda-structure-filter ((t (:foreground ,orange))))
   `(org-agenda-date ((t (:foreground ,subtle-1))))
   `(org-agenda-date-today ((t (:foreground ,pink :weight bold))))
   `(org-agenda-date-weekend ((t (:foreground ,blue-soft))))
   `(org-agenda-done ((t (:foreground ,fg-dim))))
   `(org-agenda-dimmed-todo-face ((t (:foreground ,fg-dim))))
   `(org-agenda-current-time ((t (:foreground ,pink :weight bold))))
   `(org-agenda-clocking ((t (:background ,bg-visual))))
   `(org-agenda-calendar-event ((t (:foreground ,subtle-1))))
   `(org-agenda-calendar-sexp ((t (:foreground ,magenta))))
   `(org-agenda-filter-category ((t (:foreground ,orange))))
   `(org-agenda-filter-tags ((t (:foreground ,magenta))))
   `(org-agenda-filter-effort ((t (:foreground ,identifier))))
   `(org-habit-clear-face ((t (:background ,bg-visual))))
   `(org-habit-clear-future-face ((t (:background ,bg-cursor))))
   `(org-habit-ready-face ((t (:background ,paren-bg))))
   `(org-habit-ready-future-face ((t (:background ,paren-bg))))
   `(org-habit-alert-face ((t (:background ,warning-bg))))
   `(org-habit-alert-future-face ((t (:background ,warning-bg))))
   `(org-habit-overdue-face ((t (:background ,error-bg))))
   `(org-habit-overdue-future-face ((t (:background ,error-bg))))

;;;; org-roam / org-download
   `(org-roam-header-line ((t (:foreground ,subtle-1 :weight bold))))
   `(org-roam-title ((t (:foreground ,pink :weight bold))))
   `(org-roam-olp ((t (:foreground ,fg-dim))))
   `(org-roam-preview-heading ((t (:foreground ,subtle-1 :weight bold))))
   `(org-roam-preview-heading-highlight ((t (:background ,bg-cursor))))
   `(org-roam-preview-heading-selection ((t (:background ,bg-visual))))
   `(org-roam-preview-region ((t (:background ,bg-alt))))
   `(org-roam-dim ((t (:foreground ,fg-dim))))

;;;; org-fc
   `(org-fc-type-cloze-hole-face ((t (:foreground ,subtle-1 :weight bold))))

;;;; Markdown
   `(markdown-header-face ((t (:foreground ,subtle-1 :weight bold))))
   `(markdown-header-face-1 ((t (:foreground ,pink :weight bold :height 1.3))))
   `(markdown-header-face-2 ((t (:foreground ,subtle-1 :weight bold :height 1.2))))
   `(markdown-header-face-3 ((t (:foreground ,identifier :weight bold :height 1.1))))
   `(markdown-header-face-4 ((t (:foreground ,orange :weight bold))))
   `(markdown-header-face-5 ((t (:foreground ,magenta :weight bold))))
   `(markdown-header-face-6 ((t (:foreground ,type :weight bold))))
   `(markdown-header-delimiter-face ((t (:foreground ,fg-dim))))
   `(markdown-header-rule-face ((t (:foreground ,fg-dim))))
   `(markdown-markup-face ((t (:foreground ,fg-dim))))
   `(markdown-list-face ((t (:foreground ,identifier))))
   `(markdown-link-face ((t (:inherit link))))
   `(markdown-url-face ((t (:foreground ,string :underline t))))
   `(markdown-link-title-face ((t (:foreground ,magenta))))
   `(markdown-reference-face ((t (:foreground ,blue-soft))))
   `(markdown-footnote-marker-face ((t (:foreground ,blue-soft))))
   `(markdown-footnote-text-face ((t (:foreground ,fg-dim :slant italic))))
   `(markdown-inline-code-face ((t (:foreground ,regex :background ,bg-alt))))
   `(markdown-pre-face ((t (:foreground ,regex :background ,bg-alt))))
   `(markdown-code-face ((t (:foreground ,fg :background ,bg-alt :extend t))))
   `(markdown-language-keyword-face ((t (:foreground ,keyword))))
   `(markdown-language-info-face ((t (:foreground ,type))))
   `(markdown-italic-face ((t (:slant italic))))
   `(markdown-bold-face ((t (:weight bold))))
   `(markdown-blockquote-face ((t (:foreground ,fg-dim :slant italic))))
   `(markdown-line-break-face ((t (:underline t))))
   `(markdown-comment-face ((t (:inherit font-lock-comment-face))))
   `(markdown-metadata-key-face ((t (:foreground ,keyword))))
   `(markdown-metadata-value-face ((t (:foreground ,string))))
   `(markdown-gfm-checkbox-face ((t (:foreground ,identifier))))
   `(markdown-highlight-face ((t (:background ,bg-pmenu-sel))))
   `(markdown-html-tag-name-face ((t (:foreground ,cyan-bright :weight bold))))
   `(markdown-html-attr-name-face ((t (:foreground ,orange-soft))))
   `(markdown-html-attr-value-face ((t (:foreground ,string))))
   `(markdown-html-entity-face ((t (:foreground ,negation))))
   `(markdown-table-face ((t (:foreground ,subtle-1 :background ,bg-alt))))

;;;; Rainbow delimiters
   `(rainbow-delimiters-depth-1-face ((t (:foreground "red" :weight bold))))
   `(rainbow-delimiters-depth-2-face ((t (:foreground "green" :weight bold))))
   `(rainbow-delimiters-depth-3-face ((t (:foreground "cyan" :weight bold))))
   `(rainbow-delimiters-depth-4-face ((t (:foreground "yellow" :weight bold))))
   `(rainbow-delimiters-depth-5-face ((t (:foreground "magenta" :weight bold))))
   `(rainbow-delimiters-depth-6-face ((t (:foreground "teal" :weight bold))))
   `(rainbow-delimiters-depth-7-face ((t (:foreground "orange" :weight bold))))
   `(rainbow-delimiters-depth-8-face ((t (:foreground "pink" :weight bold))))
   `(rainbow-delimiters-depth-9-face ((t (:foreground "purple" :weight bold))))
   `(rainbow-delimiters-unmatched-face ((t (:foreground "white" :weight bold))))
   `(rainbow-delimiters-mismatched-face ((t (:foreground ,error-fg :background ,error-bg :weight bold))))
   `(rainbow-delimiters-base-error-face ((t (:inherit rainbow-delimiters-unmatched-face))))

;;;; Smartparens
   `(sp-pair-overlay-face ((t (:background ,bg-cursor))))
   `(sp-wrap-overlay-face ((t (:background ,bg-cursor))))
   `(sp-wrap-tag-overlay-face ((t (:background ,bg-cursor))))
   `(sp-show-pair-match-face ((t (:inherit show-paren-match))))
   `(sp-show-pair-mismatch-face ((t (:inherit show-paren-mismatch))))
   `(sp-show-pair-enclosing ((t (:inherit show-paren-match))))

;;;; hideshow
   `(hs-face ((t (:background ,bg-alt))))
   `(hs-fringe-face ((t (:foreground ,fg-dim))))

;;;; Company
   `(company-echo-common ((t (:foreground ,string))))
   `(company-preview ((t (:inherit company-tooltip-selection))))
   `(company-preview-common ((t (:inherit company-preview))))
   `(company-preview-search ((t (:inherit company-preview))))
   `(company-scrollbar-bg ((t (:background ,subtle-1))))
   `(company-scrollbar-fg ((t (:background ,subtle-2))))
   `(company-tooltip ((t (:foreground ,fg :background ,bg-pmenu))))
   `(company-tooltip-annotation ((t (:inherit company-tooltip :foreground ,pink))))
   `(company-tooltip-annotation-selection ((t (:inherit company-tooltip-selection :foreground ,pink))))
   `(company-tooltip-common ((t (:foreground ,search-bg :weight bold))))
   `(company-tooltip-common-selection ((t (:foreground ,search-bg :background ,bg-pmenu-sel :weight bold))))
   `(company-tooltip-mouse ((t (:foreground ,fg :background ,bg-pmenu-sel))))
   `(company-tooltip-search ((t (:inherit company-tooltip :background ,search-bg :foreground ,search-fg))))
   `(company-tooltip-search-selection ((t (:inherit company-tooltip-selection))))
   `(company-tooltip-selection ((t (:foreground ,fg :background ,bg-pmenu-sel))))
   `(company-tooltip-deprecated ((t (:foreground ,fg-dim :strike-through t))))
   `(company-tooltip-quick-access ((t (:foreground ,orange))))
   `(company-tooltip-quick-access-selection ((t (:foreground ,orange :background ,bg-pmenu-sel))))
   `(company-template-field ((t (:foreground ,search-fg :background ,search-bg))))

;;;; Ivy / Counsel / Swiper
   `(ivy-current-match ((t (:foreground ,fg :background ,bg-pmenu-sel :weight bold :extend t))))
   `(ivy-confirm-face ((t (:foreground ,success-fg))))
   `(ivy-match-required-face ((t (:foreground ,error-fg))))
   `(ivy-minibuffer-match-face-1 ((t (:foreground ,fg :background ,bg-alt))))
   `(ivy-minibuffer-match-face-2 ((t (:foreground ,pink :weight bold))))
   `(ivy-minibuffer-match-face-3 ((t (:foreground ,subtle-1 :weight bold))))
   `(ivy-minibuffer-match-face-4 ((t (:foreground ,identifier :weight bold))))
   `(ivy-minibuffer-match-highlight ((t (:foreground ,pink :weight bold))))
   `(ivy-subdir ((t (:foreground ,identifier :weight bold))))
   `(ivy-modified-buffer ((t (:foreground ,orange))))
   `(ivy-modified-outside-buffer ((t (:foreground ,warning-fg))))
   `(ivy-remote ((t (:foreground ,magenta))))
   `(ivy-virtual ((t (:foreground ,fg-dim :slant italic))))
   `(ivy-action ((t (:foreground ,magenta))))
   `(ivy-highlight-face ((t (:foreground ,orange))))
   `(ivy-grep-info ((t (:foreground ,identifier))))
   `(ivy-grep-line-number ((t (:foreground ,fg-dim))))
   `(ivy-completions-annotations ((t (:foreground ,fg-dim :slant italic))))
   `(ivy-yanked-word ((t (:foreground ,search-bg))))
   `(ivy-cursor ((t (:foreground ,bg :background ,fg))))
   `(ivy-separator ((t (:foreground ,fg-dim))))
   `(ivy-prompt-match ((t (:inherit ivy-current-match))))
   `(counsel-active-mode ((t (:foreground ,identifier))))
   `(counsel-application-name ((t (:foreground ,orange))))
   `(counsel-key-binding ((t (:foreground ,pink :weight bold))))
   `(counsel-outline-default ((t (:inherit font-lock-doc-face))))
   `(counsel-outline-1 ((t (:inherit outline-1))))
   `(counsel-outline-2 ((t (:inherit outline-2))))
   `(counsel-outline-3 ((t (:inherit outline-3))))
   `(counsel-outline-4 ((t (:inherit outline-4))))
   `(counsel-outline-5 ((t (:inherit outline-5))))
   `(counsel-outline-6 ((t (:inherit outline-6))))
   `(counsel-outline-7 ((t (:inherit outline-7))))
   `(counsel-outline-8 ((t (:inherit outline-8))))
   `(counsel-variable-documentation ((t (:foreground ,comment-fg :slant italic))))
   `(swiper-match-face-1 ((t (:foreground ,fg :background ,bg-alt))))
   `(swiper-match-face-2 ((t (:foreground ,pink :weight bold))))
   `(swiper-match-face-3 ((t (:foreground ,subtle-1 :weight bold))))
   `(swiper-match-face-4 ((t (:foreground ,identifier :weight bold))))
   `(swiper-background-match-face-1 ((t (:inherit swiper-match-face-1))))
   `(swiper-background-match-face-2 ((t (:inherit swiper-match-face-2))))
   `(swiper-background-match-face-3 ((t (:inherit swiper-match-face-3))))
   `(swiper-background-match-face-4 ((t (:inherit swiper-match-face-4))))
   `(swiper-line-face ((t (:background ,bg-cursor :extend t))))

;;;; Vertico / Marginalia / Orderless
   `(vertico-current ((t (:foreground ,fg :background ,bg-pmenu-sel :weight bold :extend t))))
   `(vertico-group-separator ((t (:foreground ,fg-dim :strike-through t))))
   `(vertico-group-title ((t (:foreground ,subtle-1 :weight bold))))
   `(vertico-multiline ((t (:foreground ,fg-dim))))
   `(marginalia-archive ((t (:foreground ,magenta))))
   `(marginalia-char ((t (:foreground ,pink))))
   `(marginalia-date ((t (:foreground ,blue-soft))))
   `(marginalia-documentation ((t (:inherit font-lock-doc-face))))
   `(marginalia-file-name ((t (:foreground ,fg))))
   `(marginalia-file-owner ((t (:foreground ,magenta))))
   `(marginalia-file-priv-dir ((t (:foreground ,identifier))))
   `(marginalia-file-priv-exec ((t (:foreground ,success-fg))))
   `(marginalia-file-priv-link ((t (:foreground ,magenta))))
   `(marginalia-file-priv-no ((t (:foreground ,fg-dim))))
   `(marginalia-file-priv-other ((t (:foreground ,orange))))
   `(marginalia-file-priv-rare ((t (:foreground ,pink))))
   `(marginalia-file-priv-read ((t (:foreground ,subtle-1))))
   `(marginalia-file-priv-write ((t (:foreground ,warning-fg))))
   `(marginalia-function ((t (:foreground ,func))))
   `(marginalia-key ((t (:foreground ,pink :weight bold))))
   `(marginalia-lighter ((t (:foreground ,orange))))
   `(marginalia-list ((t (:foreground ,magenta))))
   `(marginalia-mode ((t (:foreground ,identifier))))
   `(marginalia-modified ((t (:foreground ,orange))))
   `(marginalia-null ((t (:foreground ,fg-dim))))
   `(marginalia-number ((t (:foreground ,number))))
   `(marginalia-off ((t (:foreground ,fg-dim))))
   `(marginalia-on ((t (:foreground ,success-fg))))
   `(marginalia-size ((t (:foreground ,blue-soft))))
   `(marginalia-string ((t (:foreground ,string))))
   `(marginalia-symbol ((t (:foreground ,type))))
   `(marginalia-true ((t (:foreground ,success-fg))))
   `(marginalia-type ((t (:foreground ,type))))
   `(marginalia-value ((t (:foreground ,constant))))
   `(marginalia-version ((t (:foreground ,blue-soft))))
   `(orderless-match-face-0 ((t (:foreground ,pink :weight bold))))
   `(orderless-match-face-1 ((t (:foreground ,subtle-1 :weight bold))))
   `(orderless-match-face-2 ((t (:foreground ,identifier :weight bold))))
   `(orderless-match-face-3 ((t (:foreground ,orange :weight bold))))

;;;; Which-key
   `(which-key-key-face ((t (:foreground ,pink :weight bold))))
   `(which-key-separator-face ((t (:foreground ,fg-dim))))
   `(which-key-note-face ((t (:foreground ,fg-dim :slant italic))))
   `(which-key-command-description-face ((t (:foreground ,fg))))
   `(which-key-local-map-description-face ((t (:foreground ,identifier))))
   `(which-key-group-description-face ((t (:foreground ,subtle-1 :weight bold))))
   `(which-key-highlighted-command-face ((t (:foreground ,orange :underline t))))
   `(which-key-special-key-face ((t (:foreground ,pink :weight bold))))

;;;; Transient / hydra
   `(transient-key ((t (:foreground ,pink :weight bold))))
   `(transient-key-exit ((t (:inherit transient-key))))
   `(transient-key-noop ((t (:foreground ,fg-dim))))
   `(transient-key-return ((t (:inherit transient-key))))
   `(transient-key-stay ((t (:inherit transient-key))))
   `(transient-heading ((t (:foreground ,subtle-1 :weight bold))))
   `(transient-argument ((t (:foreground ,identifier :weight bold))))
   `(transient-active-infix ((t (:background ,bg-pmenu-sel))))
   `(transient-enabled-suffix ((t (:foreground ,bg :background ,success-fg :weight bold))))
   `(transient-disabled-suffix ((t (:foreground ,fg :background ,fg-dimmer))))
   `(transient-inactive-argument ((t (:foreground ,fg-dim))))
   `(transient-inactive-value ((t (:foreground ,fg-dim))))
   `(transient-inapt-suffix ((t (:foreground ,fg-dim :slant italic))))
   `(transient-separator ((t (:background ,bg-visual :extend t))))
   `(transient-unreachable ((t (:foreground ,fg-dim))))
   `(transient-unreachable-key ((t (:foreground ,fg-dim))))
   `(transient-value ((t (:foreground ,string))))
   `(hydra-face-red ((t (:foreground ,preproc :weight bold))))
   `(hydra-face-blue ((t (:foreground ,subtle-1 :weight bold))))
   `(hydra-face-amaranth ((t (:foreground ,magenta :weight bold))))
   `(hydra-face-pink ((t (:foreground ,pink :weight bold))))
   `(hydra-face-teal ((t (:foreground ,type :weight bold))))

;;;; Evil
   `(evil-ex-info ((t (:foreground ,subtle-1))))
   `(evil-ex-search ((t (:inherit isearch))))
   `(evil-ex-substitute-matches ((t (:foreground ,error-fg :background ,error-bg :weight bold))))
   `(evil-ex-substitute-replacement ((t (:foreground ,success-fg :background ,paren-bg :weight bold))))
   `(evil-ex-lazy-highlight ((t (:inherit lazy-highlight))))

;;;; Magit
   `(magit-section-heading ((t (:foreground ,subtle-1 :weight bold))))
   `(magit-section-heading-selection ((t (:foreground ,pink :weight bold))))
   `(magit-section-highlight ((t (:background ,bg-cursor :extend t))))
   `(magit-section-secondary-heading ((t (:foreground ,subtle-1 :weight bold))))
   `(magit-section-child-count ((t (:foreground ,fg-dim))))
   `(magit-header-line ((t (:foreground ,subtle-1 :weight bold))))
   `(magit-header-line-key ((t (:inherit which-key-key-face))))
   `(magit-header-line-log-select ((t (:foreground ,subtle-1 :weight bold))))
   `(magit-branch-current ((t (:foreground ,pink :weight bold :box t))))
   `(magit-branch-local ((t (:foreground ,pink :weight bold))))
   `(magit-branch-remote ((t (:foreground ,identifier :weight bold))))
   `(magit-branch-remote-head ((t (:foreground ,identifier :weight bold :box t))))
   `(magit-branch-upstream ((t (:foreground ,subtle-1 :slant italic))))
   `(magit-branch-warning ((t (:foreground ,warning-fg))))
   `(magit-tag ((t (:foreground ,orange :weight bold))))
   `(magit-head ((t (:inherit magit-branch-local))))
   `(magit-refname ((t (:foreground ,magenta))))
   `(magit-refname-pullreq ((t (:foreground ,magenta))))
   `(magit-refname-stash ((t (:foreground ,magenta))))
   `(magit-refname-wip ((t (:foreground ,magenta))))
   `(magit-hash ((t (:foreground ,fg-dim))))
   `(magit-dimmed ((t (:foreground ,fg-dim))))
   `(magit-filename ((t (:foreground ,subtle-1))))
   `(magit-log-author ((t (:foreground ,magenta))))
   `(magit-log-date ((t (:foreground ,fg-dim))))
   `(magit-log-graph ((t (:foreground ,fg-dim))))
   `(magit-reflog-amend ((t (:foreground ,magenta :weight bold))))
   `(magit-reflog-checkout ((t (:foreground ,subtle-1 :weight bold))))
   `(magit-reflog-cherry-pick ((t (:foreground ,success-fg :weight bold))))
   `(magit-reflog-commit ((t (:foreground ,success-fg :weight bold))))
   `(magit-reflog-merge ((t (:foreground ,success-fg :weight bold))))
   `(magit-reflog-other ((t (:foreground ,subtle-1 :weight bold))))
   `(magit-reflog-rebase ((t (:foreground ,magenta :weight bold))))
   `(magit-reflog-remote ((t (:foreground ,subtle-1 :weight bold))))
   `(magit-reflog-reset ((t (:foreground ,error-fg :weight bold))))
   `(magit-cherry-equivalent ((t (:foreground ,magenta))))
   `(magit-cherry-unmatched ((t (:foreground ,type))))
   `(magit-signature-bad ((t (:foreground ,error-fg :weight bold))))
   `(magit-signature-error ((t (:foreground ,error-fg))))
   `(magit-signature-expired ((t (:foreground ,orange))))
   `(magit-signature-expired-key ((t (:foreground ,orange))))
   `(magit-signature-good ((t (:foreground ,success-fg :weight bold))))
   `(magit-signature-revoked ((t (:foreground ,magenta))))
   `(magit-signature-untrusted ((t (:foreground ,orange))))
   `(magit-sequence-drop ((t (:foreground ,error-fg))))
   `(magit-sequence-done ((t (:foreground ,fg-dim))))
   `(magit-sequence-exec ((t (:foreground ,magenta))))
   `(magit-sequence-head ((t (:foreground ,subtle-1))))
   `(magit-sequence-onto ((t (:foreground ,fg-dim))))
   `(magit-sequence-part ((t (:foreground ,orange))))
   `(magit-sequence-pick ((t (:foreground ,fg))))
   `(magit-sequence-stop ((t (:foreground ,error-fg))))
   `(magit-bisect-bad ((t (:foreground ,error-fg))))
   `(magit-bisect-good ((t (:foreground ,success-fg))))
   `(magit-bisect-skip ((t (:foreground ,orange))))
   `(magit-blame-date ((t (:foreground ,fg-dim))))
   `(magit-blame-hash ((t (:foreground ,fg-dim))))
   `(magit-blame-heading ((t (:foreground ,subtle-1 :background ,bg-alt :extend t))))
   `(magit-blame-highlight ((t (:background ,bg-cursor :extend t))))
   `(magit-blame-margin ((t (:foreground ,fg-dim :background ,bg-alt :extend t))))
   `(magit-blame-name ((t (:foreground ,magenta))))
   `(magit-blame-summary ((t (:foreground ,fg))))
   `(magit-diff-added ((t (:foreground ,git-add :background ,bg-alt :extend t))))
   `(magit-diff-added-highlight
     ((t (:foreground ,git-add :background ,bg-cursor :extend t :weight bold))))
   `(magit-diff-removed ((t (:foreground ,git-delete :background ,bg-alt :extend t))))
   `(magit-diff-removed-highlight
     ((t (:foreground ,git-delete :background ,bg-cursor :extend t :weight bold))))
   `(magit-diff-base ((t (:foreground ,git-change :background ,bg-alt :extend t))))
   `(magit-diff-base-highlight
     ((t (:foreground ,git-change :background ,bg-cursor :extend t :weight bold))))
   `(magit-diff-context ((t (:foreground ,fg-dim :background ,bg :extend t))))
   `(magit-diff-context-highlight ((t (:foreground ,fg :background ,bg-cursor :extend t))))
   `(magit-diff-file-heading ((t (:foreground ,pink :weight bold :extend t))))
   `(magit-diff-file-heading-highlight ((t (:background ,bg-cursor :weight bold :extend t))))
   `(magit-diff-file-heading-selection
     ((t (:foreground ,pink :background ,bg-cursor :weight bold :extend t))))
   `(magit-diff-hunk-heading ((t (:foreground ,orange :background ,bg-alt :extend t))))
   `(magit-diff-hunk-heading-highlight
     ((t (:foreground ,orange :background ,bg-cursor :extend t))))
   `(magit-diff-hunk-heading-selection
     ((t (:foreground ,pink :background ,bg-cursor :extend t))))
   `(magit-diff-lines-heading ((t (:foreground ,fg :background ,bg-visual :extend t))))
   `(magit-diff-lines-boundary ((t (:background ,bg-visual))))
   `(magit-diff-conflict-heading ((t (:foreground ,error-fg :background ,bg-alt :weight bold :extend t))))
   `(magit-diff-revision-summary ((t (:foreground ,pink :weight bold))))
   `(magit-diff-revision-summary-highlight
     ((t (:foreground ,pink :background ,bg-cursor :weight bold))))
   `(magit-diff-whitespace-warning ((t (:inherit trailing-whitespace))))
   `(magit-diffstat-added ((t (:foreground ,git-add))))
   `(magit-diffstat-removed ((t (:foreground ,git-delete))))
   `(magit-process-ng ((t (:foreground ,error-fg :weight bold))))
   `(magit-process-ok ((t (:foreground ,success-fg :weight bold))))
   `(magit-keyword ((t (:foreground ,keyword))))
   `(magit-keyword-squash ((t (:foreground ,orange))))
   `(magit-popup-argument ((t (:foreground ,identifier :weight bold))))
   `(magit-popup-disabled-argument ((t (:foreground ,fg-dim))))
   `(magit-popup-heading ((t (:foreground ,subtle-1 :weight bold))))
   `(magit-popup-key ((t (:foreground ,pink :weight bold))))
   `(magit-popup-option-value ((t (:foreground ,magenta :weight bold))))

;;;; Tide
   `(tide-file ((t (:foreground ,subtle-1 :underline t))))
   `(tide-line-number ((t (:foreground ,identifier))))
   `(tide-hl-identifier-face ((t (:background ,bg-visual))))
   `(tide-choose-overlay-face ((t (:foreground ,orange :weight bold))))
   `(tide-imenu-type-face ((t (:foreground ,type))))
   `(tide-match-highlight-face ((t (:background ,bg-visual))))

;;;; LSP
   `(lsp-face-highlight-textual ((t (:background ,bg-visual))))
   `(lsp-face-highlight-read ((t (:background ,bg-visual :underline t))))
   `(lsp-face-highlight-write ((t (:background ,bg-visual :weight bold))))
   `(lsp-face-semhl-constant ((t (:inherit font-lock-constant-face))))
   `(lsp-face-semhl-variable ((t (:inherit font-lock-variable-name-face))))
   `(lsp-face-semhl-function ((t (:inherit font-lock-function-name-face))))
   `(lsp-face-semhl-method ((t (:inherit font-lock-function-name-face))))
   `(lsp-face-semhl-class ((t (:inherit font-lock-type-face))))
   `(lsp-face-semhl-type ((t (:inherit font-lock-type-face))))
   `(lsp-face-semhl-interface ((t (:inherit font-lock-type-face))))
   `(lsp-face-semhl-enum ((t (:inherit font-lock-type-face))))
   `(lsp-face-semhl-keyword ((t (:inherit font-lock-keyword-face))))
   `(lsp-face-semhl-macro ((t (:foreground ,macro))))
   `(lsp-face-semhl-namespace ((t (:foreground ,constant))))
   `(lsp-face-semhl-parameter ((t (:foreground ,identifier :slant italic))))
   `(lsp-face-semhl-property ((t (:foreground ,identifier))))
   `(lsp-face-semhl-string ((t (:inherit font-lock-string-face))))
   `(lsp-face-semhl-comment ((t (:inherit font-lock-comment-face))))
   `(lsp-face-semhl-deprecated ((t (:strike-through t))))
   `(lsp-lens-face ((t (:foreground ,fg-dim :height 0.85))))
   `(lsp-lens-mouse-face ((t (:foreground ,subtle-1 :height 0.85 :underline t))))
   `(lsp-headerline-breadcrumb-path-face ((t (:foreground ,fg-dim))))
   `(lsp-headerline-breadcrumb-path-error-face ((t (:foreground ,error-fg :underline t))))
   `(lsp-headerline-breadcrumb-path-warning-face ((t (:foreground ,warning-fg :underline t))))
   `(lsp-headerline-breadcrumb-path-info-face ((t (:foreground ,subtle-1 :underline t))))
   `(lsp-headerline-breadcrumb-path-hint-face ((t (:foreground ,subtle-1 :underline t))))
   `(lsp-headerline-breadcrumb-separator-face ((t (:foreground ,fg-dim))))
   `(lsp-headerline-breadcrumb-project-prefix-face ((t (:foreground ,pink :weight bold))))
   `(lsp-headerline-breadcrumb-symbols-face ((t (:foreground ,subtle-1 :weight bold))))
   `(lsp-ui-doc-background ((t (:background ,bg-alt))))
   `(lsp-ui-doc-header ((t (:foreground ,subtle-1 :weight bold))))
   `(lsp-ui-doc-url ((t (:inherit link))))
   `(lsp-ui-peek-filename ((t (:foreground ,pink))))
   `(lsp-ui-peek-header ((t (:foreground ,subtle-1 :background ,bg-alt :weight bold))))
   `(lsp-ui-peek-highlight ((t (:background ,bg-pmenu-sel))))
   `(lsp-ui-peek-line-number ((t (:foreground ,identifier))))
   `(lsp-ui-peek-list ((t (:background ,bg-alt))))
   `(lsp-ui-peek-peek ((t (:background ,bg-alt))))
   `(lsp-ui-peek-selection ((t (:background ,bg-pmenu-sel))))
   `(lsp-ui-sideline-code-action ((t (:foreground ,orange))))
   `(lsp-ui-sideline-current-symbol ((t (:foreground ,pink :weight bold))))
   `(lsp-ui-sideline-symbol ((t (:foreground ,fg-dim))))
   `(lsp-ui-sideline-symbol-info ((t (:foreground ,fg-dim :slant italic))))
   `(lsp-installation-finished-face ((t (:foreground ,success-fg))))

;;;; Eglot
   `(eglot-highlight-symbol-face ((t (:background ,bg-visual))))
   `(eglot-diagnostic-tag-unnecessary-face ((t (:inherit shadow))))
   `(eglot-diagnostic-tag-deprecated-face ((t (:strike-through t))))
   `(eglot-mode-line ((t (:foreground ,fg :weight bold))))

;;;; Tree-sitter
   `(tree-sitter-hl-face:attribute ((t (:inherit font-lock-preprocessor-face))))
   `(tree-sitter-hl-face:comment ((t (:inherit font-lock-comment-face))))
   `(tree-sitter-hl-face:constant ((t (:inherit font-lock-constant-face))))
   `(tree-sitter-hl-face:constant.builtin ((t (:inherit font-lock-builtin-face))))
   `(tree-sitter-hl-face:constructor ((t (:inherit font-lock-type-face))))
   `(tree-sitter-hl-face:doc ((t (:inherit font-lock-doc-face))))
   `(tree-sitter-hl-face:escape ((t (:foreground ,negation))))
   `(tree-sitter-hl-face:function ((t (:inherit font-lock-function-name-face))))
   `(tree-sitter-hl-face:function.builtin ((t (:foreground ,constant))))
   `(tree-sitter-hl-face:function.call ((t (:inherit font-lock-function-name-face))))
   `(tree-sitter-hl-face:function.macro ((t (:foreground ,macro))))
   `(tree-sitter-hl-face:function.method ((t (:inherit font-lock-function-name-face))))
   `(tree-sitter-hl-face:function.special ((t (:foreground ,pink :weight bold))))
   `(tree-sitter-hl-face:keyword ((t (:inherit font-lock-keyword-face))))
   `(tree-sitter-hl-face:label ((t (:foreground ,label))))
   `(tree-sitter-hl-face:method ((t (:inherit font-lock-function-name-face))))
   `(tree-sitter-hl-face:method.call ((t (:inherit font-lock-function-name-face))))
   `(tree-sitter-hl-face:number ((t (:inherit font-lock-number-face))))
   `(tree-sitter-hl-face:operator ((t (:inherit font-lock-operator-face))))
   `(tree-sitter-hl-face:property ((t (:foreground ,identifier))))
   `(tree-sitter-hl-face:property.definition ((t (:foreground ,identifier :slant italic))))
   `(tree-sitter-hl-face:punctuation ((t (:inherit font-lock-punctuation-face))))
   `(tree-sitter-hl-face:punctuation.bracket ((t (:inherit font-lock-bracket-face))))
   `(tree-sitter-hl-face:punctuation.delimiter ((t (:inherit font-lock-delimiter-face))))
   `(tree-sitter-hl-face:punctuation.special ((t (:foreground ,pink))))
   `(tree-sitter-hl-face:string ((t (:inherit font-lock-string-face))))
   `(tree-sitter-hl-face:string.special ((t (:foreground ,regex))))
   `(tree-sitter-hl-face:tag ((t (:foreground ,cyan-bright :weight bold))))
   `(tree-sitter-hl-face:type ((t (:inherit font-lock-type-face))))
   `(tree-sitter-hl-face:type.builtin ((t (:inherit font-lock-type-face :weight bold))))
   `(tree-sitter-hl-face:type.parameter ((t (:inherit font-lock-type-face :slant italic))))
   `(tree-sitter-hl-face:type.super ((t (:inherit font-lock-type-face :underline t))))
   `(tree-sitter-hl-face:variable ((t (:inherit font-lock-variable-name-face))))
   `(tree-sitter-hl-face:variable.builtin ((t (:inherit font-lock-builtin-face))))
   `(tree-sitter-hl-face:variable.parameter ((t (:foreground ,identifier :slant italic))))
   `(tree-sitter-hl-face:variable.special ((t (:foreground ,variable :weight bold))))
   `(tree-sitter-hl-face:embedded ((t (:foreground ,magenta))))

;;;; Web-mode
   `(web-mode-html-tag-face ((t (:foreground ,cyan-bright :weight bold))))
   `(web-mode-html-tag-bracket-face ((t (:foreground ,cyan-bright))))
   `(web-mode-html-tag-custom-face ((t (:foreground ,identifier))))
   `(web-mode-html-tag-unclosed-face ((t (:foreground ,cyan-bright :underline t))))
   `(web-mode-html-attr-name-face ((t (:foreground ,orange-soft))))
   `(web-mode-html-attr-value-face ((t (:foreground ,string))))
   `(web-mode-html-attr-equal-face ((t (:foreground ,operator))))
   `(web-mode-html-attr-custom-face ((t (:foreground ,orange-soft :slant italic))))
   `(web-mode-html-attr-engine-face ((t (:foreground ,pink))))
   `(web-mode-html-entity-face ((t (:foreground ,negation))))
   `(web-mode-doctype-face ((t (:foreground ,fg-dim :slant italic))))
   `(web-mode-comment-face ((t (:inherit font-lock-comment-face))))
   `(web-mode-preprocessor-face ((t (:inherit font-lock-preprocessor-face))))
   `(web-mode-string-face ((t (:inherit font-lock-string-face))))
   `(web-mode-builtin-face ((t (:inherit font-lock-builtin-face))))
   `(web-mode-constant-face ((t (:inherit font-lock-constant-face))))
   `(web-mode-type-face ((t (:inherit font-lock-type-face))))
   `(web-mode-keyword-face ((t (:inherit font-lock-keyword-face))))
   `(web-mode-function-name-face ((t (:inherit font-lock-function-name-face))))
   `(web-mode-variable-name-face ((t (:inherit font-lock-variable-name-face))))
   `(web-mode-symbol-face ((t (:foreground ,pink))))
   `(web-mode-css-property-name-face ((t (:foreground ,identifier :weight bold))))
   `(web-mode-css-selector-face ((t (:foreground ,pink :weight bold))))
   `(web-mode-css-pseudo-class-face ((t (:foreground ,magenta))))
   `(web-mode-css-at-rule-face ((t (:foreground ,orange))))
   `(web-mode-css-function-face ((t (:foreground ,func))))
   `(web-mode-css-variable-face ((t (:foreground ,variable))))
   `(web-mode-css-string-face ((t (:inherit font-lock-string-face))))
   `(web-mode-css-color-face ((t (:foreground ,orange-soft :weight bold))))
   `(web-mode-json-comment-face ((t (:inherit font-lock-comment-face))))
   `(web-mode-json-context-face ((t (:foreground ,magenta))))
   `(web-mode-json-key-face ((t (:foreground ,subtle-1))))
   `(web-mode-json-string-face ((t (:inherit font-lock-string-face))))
   `(web-mode-block-face ((t (:background ,bg-alt :extend t))))
   `(web-mode-block-delimiter-face ((t (:foreground ,preproc :weight bold))))
   `(web-mode-block-control-face ((t (:foreground ,preproc :weight bold))))
   `(web-mode-block-attr-name-face ((t (:foreground ,orange-soft))))
   `(web-mode-block-attr-value-face ((t (:foreground ,string))))
   `(web-mode-block-comment-face ((t (:inherit font-lock-comment-face))))
   `(web-mode-block-string-face ((t (:inherit font-lock-string-face))))
   `(web-mode-current-element-highlight-face ((t (:background ,bg-visual))))
   `(web-mode-current-column-highlight-face ((t (:background ,bg-cursor))))
   `(web-mode-inlay-face ((t (:background ,bg-alt))))
   `(web-mode-whitespace-face ((t (:background ,todo-bg))))
   `(web-mode-error-face ((t (:foreground ,error-fg :background ,error-bg))))
   `(web-mode-warning-face ((t (:foreground ,warning-fg :background ,warning-bg))))

;;;; Pulsar
   `(pulsar-red ((t (:background ,error-bg))))
   `(pulsar-green ((t (:background ,paren-bg))))
   `(pulsar-yellow ((t (:background ,warning-bg))))
   `(pulsar-blue ((t (:background ,bg-visual))))
   `(pulsar-cyan ((t (:background ,isearch-fg))))
   `(pulsar-magenta ((t (:background "#520042"))))
   `(pulsar-generic ((t (:background ,bg-pmenu))))

;;;; ibuffer / ibuffer-sidebar / ibuffer-projectile
   `(ibuffer-locked-buffer ((t (:foreground ,warning-fg))))
   `(ibuffer-deletion-face ((t (:foreground ,error-fg :weight bold))))
   `(ibuffer-marked-face ((t (:foreground ,orange :weight bold))))
   `(ibuffer-filter-group-name-face ((t (:foreground ,subtle-1 :weight bold))))
   `(ibuffer-special-buffer-face ((t (:foreground ,fg-dim))))
   `(ibuffer-help-buffer-face ((t (:foreground ,fg-dim :slant italic))))
   `(ibuffer-dired-buffer-face ((t (:foreground ,identifier))))
   `(ibuffer-read-only-buffer-face ((t (:foreground ,warning-fg))))
   `(ibuffer-hidden-buffer-face ((t (:foreground ,fg-dim))))

;;;; yasnippet
   `(yas-field-highlight-face ((t (:foreground ,fg :background ,bg-pmenu-sel))))

;;;; Message / Gnus
   `(message-header-name ((t (:foreground ,fg-dim))))
   `(message-header-cc ((t (:foreground ,subtle-1))))
   `(message-header-to ((t (:foreground ,subtle-1 :weight bold))))
   `(message-header-newsgroups ((t (:foreground ,magenta))))
   `(message-header-other ((t (:foreground ,subtle-1))))
   `(message-header-subject ((t (:foreground ,pink :weight bold))))
   `(message-header-xheader ((t (:foreground ,fg-dim))))
   `(message-cited-text ((t (:foreground ,fg-dim :slant italic))))
   `(message-cited-text-1 ((t (:foreground ,blue-soft :slant italic))))
   `(message-cited-text-2 ((t (:foreground ,identifier :slant italic))))
   `(message-cited-text-3 ((t (:foreground ,orange :slant italic))))
   `(message-cited-text-4 ((t (:foreground ,magenta :slant italic))))
   `(message-mml ((t (:foreground ,regex))))
   `(message-separator ((t (:foreground ,fg-dim))))

;;;; Elfeed
   `(elfeed-log-debug-level-face ((t (:foreground ,fg-dim))))
   `(elfeed-log-error-level-face ((t (:inherit error))))
   `(elfeed-log-info-level-face ((t (:foreground ,subtle-1))))
   `(elfeed-log-warn-level-face ((t (:inherit warning))))
   `(elfeed-search-date-face ((t (:foreground ,blue-soft))))
   `(elfeed-search-feed-face ((t (:foreground ,identifier))))
   `(elfeed-search-filter-face ((t (:foreground ,magenta :weight bold))))
   `(elfeed-search-last-update-face ((t (:foreground ,fg-dim))))
   `(elfeed-search-tag-face ((t (:foreground ,orange))))
   `(elfeed-search-title-face ((t (:foreground ,fg))))
   `(elfeed-search-unread-count-face ((t (:foreground ,pink :weight bold))))
   `(elfeed-search-unread-title-face ((t (:foreground ,fg :weight bold))))

;;;; ace-window
   `(aw-leading-char-face ((t (:foreground ,pink :weight bold :height 2.0))))
   `(aw-background-face ((t (:foreground ,fg-dim))))
   `(aw-mode-line-face ((t (:inherit mode-line))))

;;;; restclient
   `(restclient-header-name-face ((t (:foreground ,subtle-1 :weight bold))))
   `(restclient-header-value-face ((t (:foreground ,string))))
   `(restclient-method-face ((t (:foreground ,pink :weight bold))))
   `(restclient-request-hook-face ((t (:foreground ,orange))))
   `(restclient-request-hook-name-face ((t (:foreground ,orange))))
   `(restclient-request-hook-args-face ((t (:foreground ,orange-soft))))
   `(restclient-variable-name-face ((t (:inherit font-lock-variable-name-face))))
   `(restclient-variable-string-face ((t (:inherit font-lock-string-face))))
   `(restclient-variable-elisp-face ((t (:foreground ,magenta))))
   `(restclient-variable-multiline-face ((t (:foreground ,orange))))
   `(restclient-variable-usage-face ((t (:foreground ,variable))))
   `(restclient-status-code-face ((t (:foreground ,identifier :weight bold))))

;;;; Anzu
   `(anzu-mode-line ((t (:foreground ,fg :weight bold))))
   `(anzu-mode-line-no-match ((t (:foreground ,error-fg :weight bold))))
   `(anzu-match-1 ((t (:foreground ,search-fg :background ,search-bg))))
   `(anzu-match-2 ((t (:foreground ,isearch-fg :background ,isearch-bg))))
   `(anzu-replace-highlight ((t (:foreground ,error-fg :background ,error-bg))))
   `(anzu-replace-to ((t (:foreground ,success-fg :background ,paren-bg))))

;;;; undo-tree
   `(undo-tree-visualizer-active-branch-face ((t (:foreground ,fg :weight bold))))
   `(undo-tree-visualizer-current-face ((t (:foreground ,pink :weight bold))))
   `(undo-tree-visualizer-default-face ((t (:foreground ,fg-dim))))
   `(undo-tree-visualizer-register-face ((t (:foreground ,orange))))
   `(undo-tree-visualizer-unmodified-face ((t (:foreground ,subtle-1))))

;;;; Calendar
   `(calendar-today ((t (:foreground ,pink :weight bold :underline t))))
   `(calendar-weekday-header ((t (:foreground ,subtle-1 :weight bold))))
   `(calendar-weekend-header ((t (:foreground ,blue-soft :weight bold))))
   `(calendar-month-header ((t (:foreground ,pink :weight bold))))
   `(holiday ((t (:foreground ,orange :weight bold))))
   `(diary ((t (:foreground ,magenta))))

;;;; ERT
   `(ert-test-result-expected ((t (:foreground ,success-fg :background ,paren-bg))))
   `(ert-test-result-unexpected ((t (:foreground ,error-fg :background ,error-bg))))

;;;; Speedbar / Imenu
   `(speedbar-button-face ((t (:foreground ,identifier))))
   `(speedbar-directory-face ((t (:foreground ,subtle-1 :weight bold))))
   `(speedbar-file-face ((t (:foreground ,fg))))
   `(speedbar-highlight-face ((t (:background ,bg-cursor))))
   `(speedbar-selected-face ((t (:foreground ,pink :weight bold))))
   `(speedbar-separator-face ((t (:foreground ,fg-dim))))
   `(speedbar-tag-face ((t (:foreground ,magenta))))))

;;;###autoload
(when (and (boundp 'custom-theme-load-path) load-file-name)
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'fruity)
;;; fruity-theme.el ends here
